### ISSUE TITLE
Cannot the define base class as types

### ISSUE THREAD

**Issue by jopaha** [southalc/types#2]
Hello,

I am trying to get the official apache module working with your types module.
What I´ve done in Hiera:

````
types::types:
  - 'apache'
  - 'apache::vhost'

types::apache:
    service_ensure: 'stopped'


types::apache::vhost:
  'user.example.com':
    port: '80'
    docroot: '/var/www/test'
````

The apache::vhost part is working fine. I just cannot get the "apache" part to work.
Here is the error I am getting:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Expected value of type Hash, got String (file: /etc/puppetlabs/code/environments/production/modules/types/manifests/type.pp, line: 15, column: 23) (file: /etc/puppetlabs/code/environments/production/modules/types/manifests/init.pp, line: 39) on node server1.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Can you please help me out?

**Comment by jopaha** [comment]
Solved

**Comment by southalc** [comment]
The "types" module works with Puppet resource types or defined types.  The "apache" module reference lists the defined types and resource types provided by the module:
https://forge.puppet.com/modules/puppetlabs/apache/reference#defined-types
https://forge.puppet.com/modules/puppetlabs/apache/reference#resource-types

In your example you are trying to use "apache"as a type, but it is a _class_ and not a type.  What you need to do is "include" the apache class.  This can be done using hiera, but takes a little bit of code in a manifest to make it work.  I usually put something like the following in my puppet environment under "manifests/site.pp":
```
# Include classes from hiera lookup, enabling specific exclusions
$hiera_classes                = lookup('classes',          Array[String], 'unique', [])
$hiera_exclude_classes = lookup('exclude_classes', Array[String], 'unique', [])
include  [ $hiera_classes - $hiera_exclude_classes ]
```
The above manifest enables assigning classes from hiera.  For your example you would add the "apache" class to the list of "classes" in hiera.
```
# Class assignment based on hiera lookup()
classes:
  - "apache"

types::types:
  - 'apache::vhost'

# Parameters for the "apache" class
apache:
    service_ensure: 'stopped'

types::apache::vhost:
  'user.example.com':
    port: '80'
    docroot: '/var/www/test'
```
